version: '3.10'

services:
  sf_api_demo_app:
    container_name: sf_api_demo_app
    image: rahulsaini3/sf_api_demo_app:1.0.0
    build:
      context: .
    depends_on:
      - demo_app_db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.1.3:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  demo_app_db:
    container_name: demo_app_db
    image: 'postgres:12'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
