spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://demo_app_db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
